### ISSUE TITLE
Incompleted arc not drawn

### ISSUE THREAD

**Issue by Arvkon** [mdinacci/MDRadialProgress#17]
If progressCounter is 0 (zero) and sliceDividerHidden is set to YES, the incompleted arc does not get drawn. It returns as soon as progressCounter > 0 (see pictures below).

I am using MDRadialProgress version 1.0.7, downloaded from GitHub.

![ios simulator screen shot 15 jul 2014 10 10 31 copy](https://cloud.githubusercontent.com/assets/7681406/3582152/e3d81144-0bf7-11e4-996d-c3408b71b935.png)
![ios simulator screen shot 15 jul 2014 10 10 35 copy](https://cloud.githubusercontent.com/assets/7681406/3582153/e3dc01a0-0bf7-11e4-8711-ab6006962d94.png)

**Comment by bhatti-waqas** [comment]
on iphone 6 plus the radilProgressView crashes on drawArcInContext giving EXEC_BAD_ACCESS error.
Please help me what is the matter ?

**Comment by mdinacci** [comment]
@bhatti-waqas please don't comment on an old issue. Open a new one and provide some context, I can't tell what's wrong from the description you provided.
