### ISSUE TITLE
Show percentage symbol?

### ISSUE THREAD

**Issue by fenlandersoftware** [mdinacci/MDRadialProgress#28]
Is there a way to show the percentage symbol after the number ?

**Comment by arnaudWasappli** [comment]
Still no percentage symbol? :(

**Comment by chrisfoulds** [comment]
Line 380 of MDRadialProgressView.m

Change 
text = [NSString stringWithFormat:@"%.0f", percentageCompleted];

to 

text = [NSString stringWithFormat:@"%.0f%%", percentageCompleted];

or introduce a new boolean flag and choose between the two
