### ISSUE TITLE
Crash on iphone 6 plus.

### ISSUE THREAD

**Issue by bhatti-waqas** [mdinacci/MDRadialProgress#37]
On iphone 6 plus the radilProgressView crashes on drawArcInContext giving EXEC_BAD_ACCESS error. Please help me what is the matter ?

It works one first start. then after going back to the view where the radial is placed. IT crashes ono following method.

- (void)drawArcInContext:(CGContextRef)context center:(CGPoint)center radius:(CGFloat)radius startAngle:(CGFloat)startAngle
				endAngle:(CGFloat)endAngle color:(CGColorRef)color clockwise:(BOOL)cgClockwise
{
	CGContextBeginPath(context);
	CGContextMoveToPoint(context, center.x, center.y);
	CGContextAddArc(context, center.x, center.y, radius, startAngle, endAngle, cgClockwise);
	CGContextSetFillColorWithColor(context, color);
    
	CGContextFillPath(context);  //crash on this point exc_bad_access
}

**Comment by mdinacci** [comment]
Hello @bhatti-waqas, 
thanks for your report, I'll investigate the issue. 

In the meanwhile, can you please check whether context and color are not nil before you reach the line that causes exc_bad_access ? Thanks.

**Comment by bhatti-waqas** [comment]
I have checked already.. They ain't nil. and they are working fine for other devices.
